"""
Django settings for attendance_system project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o)ct82e^5b@0c3!53w&(209n+-l!lj#s!k*s9=1w#043v^an*i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Our apps
    'axes',
    'accounts',
    'attendance',
    'leave_management',
    'reports',
    'holidays',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'attendance_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Tell Django to use our custom Employee model instead of the default User
AUTH_USER_MODEL = 'accounts.Employee'

# Email 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ayushbeladiya65@gmail.com'
EMAIL_HOST_PASSWORD = 'grbb bepz nmnu jnel'
DEFAULT_FROM_EMAIL = 'ayushbeladiya65@gmail.com'
ADMIN_EMAIL = 'ayushbeladiya65@gmail.com'

# Templates folder (create a 'templates' folder in your project root)
TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']

# Office IP addresses allowed to mark attendance
ALLOWED_OFFICE_IPS = ['127.0.0.1']

## comment out any one of this according to your need 

# OFFICE gps coordinates
# OFFICE_LATITUDE = 21.2417781
# OFFICE_LONGITUDE = 72.8809676
# OFFICE_RADIUS_METERS = 100
     
## HOME GPS coordinates
OFFICE_LATITUDE = 21.2950471
OFFICE_LONGITUDE = 72.8958814
OFFICE_RADIUS_METERS = 10000



AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Lock account after 5 failed attempts
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # locked for 1 hour
AXES_LOCKOUT_TEMPLATE = 'accounts/locked_out.html'






# Log out after 8 hours of inactivity
SESSION_COOKIE_AGE = 86400

# Session expires when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Prevent JavaScript from reading session cookie
SESSION_COOKIE_SECURE = False  # set True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Force HTTPS in production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True




