# Generated by Django 6.0.4 on 2026-04-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026)),
                ('sick_leave', models.IntegerField(default=12)),
                ('casual_leave', models.IntegerField(default=12)),
                ('annual_leave', models.IntegerField(default=15)),
                ('emergency_leave', models.IntegerField(default=5)),
                ('other_leave', models.IntegerField(default=3)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
