# Generated by Django 6.0.4 on 2026-05-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_records', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['break_start'],
            },
        ),
    ]
