# Generated by Django 6.0.4 on 2026-05-16 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_breakrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Policy', max_length=100)),
                ('office_start_time', models.TimeField(default=datetime.time(9, 30))),
                ('late_threshold_time', models.TimeField(default=datetime.time(10, 0))),
                ('default_break_enabled', models.BooleanField(default=True)),
                ('default_break_start_time', models.TimeField(default=datetime.time(13, 0))),
                ('default_break_end_time', models.TimeField(default=datetime.time(14, 0))),
                ('minimum_session_minutes', models.PositiveIntegerField(default=5)),
                ('daily_working_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ('leave_notice_hours', models.PositiveIntegerField(default=36)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Policy',
                'verbose_name_plural': 'Company Policies',
            },
        ),
    ]
